-- DCAF.Codewords = {
--     FlashGordon = { "Flash Gordon", "Prince Barin", "Ming", "Princess Aura", "Zarkov", "Klytus", "Vultan" },
--     JamesBond = { "Moneypenny", "Jaws", "Swann", "Gogol", "Tanner", "Blofeld", "Leiter" },
--     RockHeroes = { "Idol", "Dio", "Vaughan", "Lynott", "Lemmy", "Mercury", "Fogerty" },
--     Disney = { "Goofy", "Donald Duck", "Mickey", "Snow White", "Peter Pan", "Cinderella", "Baloo" },
--     Poets = { "Eliot", "Blake", "Poe", "Keats", "Shakespeare", "Yeats", "Byron", "Wilde" },
--     Painters = { "da Vinci", "van Gogh", "Rembrandt", "Monet", "Matisse", "Picasso", "Boticelli" },
--     Marvel = { "Wolverine", "Iron Man", "Thor", "Captain America", "Spider Man", "Black Widow", "Star-Lord" }
-- }

-- DCAF.CodewordTheme = {
--     ClassName = "DCAF.CodewordTheme",
--     Name = nil,
--     Codewords = {}
-- }

-- function DCAF.Codewords:RandomTheme(singleUse)
--     local key = dictRandomKey(DCAF.Codewords)
-- Debug("nisse - DCAF.Codewords:RandomTheme :: key: " .. Dump(key, DumpPrettyOptions:New():IncludeFunctions()))
--     local codewords = DCAF.Codewords[key]
--     local theme = DCAF.CodewordTheme:New(key, codewords, singleUse)
--     if isBoolean(singleUse) and singleUse == true then
--         DCAF.Codewords[key] = nil
--     end
--     return theme
--     -- return DCAF.CodewordTheme:New(key, codewords)
-- end

-- function DCAF.CodewordTheme:New(name, codewords, singleUse)
--     local theme = DCAF.clone(DCAF.CodewordTheme)
--     theme.Name = name
--     if isBoolean(singleUse) then
--         theme.SingleUse = singleUse
--     else
--         theme.SingleUse = true
--     end
--     listCopy(codewords, theme.Codewords)
--     return theme
-- end

-- function DCAF.CodewordTheme:GetNextRandom()
--     local codeword, index = listRandomItem(self.Codewords)
--     if self.SingleUse then
--         table.remove(self.Codewords, index)
--     end
--     return codeword
-- end